// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBe6X8uTKGCaEyPrsMwFZDJOucQIxtbe28',
    appId: '1:836878299351:web:fd8f2a9213a3e155868092',
    messagingSenderId: '836878299351',
    projectId: 'test-smash-gifts',
    authDomain: 'test-smash-gifts.firebaseapp.com',
    storageBucket: 'test-smash-gifts.appspot.com',
    measurementId: 'G-2EF1ZQ5Y28',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjGmYgX2QwksI-dLEzsXHC6FDzqejkuNE',
    appId: '1:836878299351:android:a28081d31d484244868092',
    messagingSenderId: '836878299351',
    projectId: 'test-smash-gifts',
    storageBucket: 'test-smash-gifts.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5VKsdT7MeYC_Udukh886OQxod85RuBZ8',
    appId: '1:836878299351:ios:68746537dfbe38c6868092',
    messagingSenderId: '836878299351',
    projectId: 'test-smash-gifts',
    storageBucket: 'test-smash-gifts.appspot.com',
    iosClientId: '836878299351-pq1a7ne7vmvsd7f4uifuf41ee4nq5a12.apps.googleusercontent.com',
    iosBundleId: 'br.com.LCostaN.smashGiftApp',
  );
}
